name: Deploy Odoo

on:
  push:
    branches:
      - main
    paths:
      - 'df_patient_registration/**'
      - 'df_patient_odontogram/**'
      - 'df_dental_voice_temp/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar deploy por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            bash /opt/detifusion/scripts/deploy.sh
