name: Restart Odoo

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Reiniciar Odoo por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            bash /opt/detifusion/scripts/restart_odoo.sh
